[package]
name = "cry_1"
version = "0.4.0"
edition = "2021"
authors = ["Nicholas Stienz <nickstienz@gmail.com>"]
license = "MIT"
description = "An assembler for the Cry_1 Computer"
repository = "https://github.com/nickstienz/cry_1"
readme = "README.md"

